added checks for wrong input

diff --git a/remove b/remove
--- a/remove
+++ b/remove
@@ -1,6 +1,18 @@
 #!/bin/bash
 
+
+# creates a recycle bin if it already doesn't exist
 if [ ! -d $HOME/deleted ] ; then
 	mkdir $HOME/deleted
 fi
 
+if [ -z $1 ] ; then
+	echo "No file name provided."
+	exit 1
+elif [ -d $1 ] ; then
+	echo "You have entered a directory. File required."
+	exit 2
+elif [ ! -e $1 ] ; then
+	echo "File does not exist"
+	exit 3
+fi
